### ISSUE TITLE
Debugging Features

### ISSUE THREAD

**Issue by kjmoon** [jehugaleahsa/FlatFiles#19]
Any plans on implementing some kind of flag for debugging so that log statements could be printed?

I realize there are a lot of format exceptions being thrown by the mapper and the stacktrace doesn't exactly tell me what the values that cause the exception are.

**Comment by jehugaleahsa** [comment]
If the error is related to invalid CSV, like missing quotes, too few
columns, etc., you would see a decent error message. I can see how I could
improve the details when a conversion fails. Let me take a stab at it.

**Comment by jehugaleahsa** [comment]
So I just pushed version 0.3.21.0 to NuGet. If a column conversion fails, there will be a message something like `Failed to convert 'a' to 'System.Int32'. Column: AccountId, Position: 0`. That too will be wrapped by an exception recording the record number.

**Comment by kjmoon** [comment]
Thanks so much! 

I've updated the package. I'm currently using a type mapper for the decimal column and I get this error.

`Encountered an invalid conversion while processing the record. Record 2.: FlatFileException
at FlatFiles.SeparatedValueReader.parseValues(String[] rawValues)
at FlatFiles.SeparatedValueReader.Read()
at FlatFiles.TypeMapping.TypedReader`1.Read()
at FlatFiles.TypeMapping.SeparatedValueTypeMapper`1.<read>d__65.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
---Type Mapper Code---
at lambda_method(Closure , Stream , Stream , ContextInfo )

at FlatFiles.Schema.parse(IColumnDefinition definition, String[] values)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
at FlatFiles.SeparatedValueReader.parseValues(String[] rawValues)
Input string was not in a correct format.: FormatException
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
at FlatFiles.DecimalColumn.Parse(String value)
at FlatFiles.Schema.parse(IColumnDefinition definition, String[] values)
`

**Comment by kjmoon** [comment]
I'm not getting the detailed error message I should be getting, such as which value the decimal parser is failing at.

**Comment by jehugaleahsa** [comment]
Look in the inner exception. The outer exception tells you what record caused the error; the inner exception tells you the specific column that caused the issue.

**Comment by kjmoon** [comment]
Unfortunately that is about all the exception I see. There is no inner exception that tells me what value caused the failure, just that it was a ParseDecimal call. 

I'm running this on dotnet core on AWS Lambda if that helps.

**Comment by jehugaleahsa** [comment]
Hmm, working in version 0.3.23.0, I created a unit test that tries to parse
a bad decimal.

[image: Inline image 2]

I ran through it with the debugger, and I can see the column details.

[image: Inline image 1]

Notice that this exception is going to get wrapped up in another
FlatFilesException.
So you have to look at the inner exception.

You'll have to provide me more details, if you're still not seeing it.


Thanks,
Travis

**Comment by kjmoon** [comment]
Yes, sorry Travis! Thanks for the update.

I'm able to see the error message after doing a dotnet restore. Currently developing in a Windows VM, pushing the code up to a git server, then pulling on my Mac to be uploaded, so I've been forgetting to dotnet restore on my Mac this entire time.

**Comment by jehugaleahsa** [comment]
Ha. No problem. Never hurts to add more tests. Thanks.
