### ISSUE TITLE
Ambiguous error SeparatedValueTypeMapper DateTime column "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by torndar** [jehugaleahsa/FlatFiles#23]
When trying to convert a null value to a DateTime instead of giving a helpful parsing error like it does for other cases I get the exception in the subject and the stack trace below. The fix is to make the property a nullable DateTime but it took a while to track it down because only a few rows in my data set have nulls in DateTime fields.

```
   at __FlatFiles_TypeMapping_read(SystemImportRecord , Object[] )
   at FlatFiles.TypeMapping.Mapper`1.<>c__DisplayClass11_0.<GetReader>b__1(Object[] values)
   at FlatFiles.TypeMapping.TypedReader`1.Read()
   at FlatFiles.TypeMapping.SeparatedValueTypeMapper`1.<read>d__69.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at APP.Business.SupplierLinkImport.x(String filename) in C:\_source\Client\application\APP.Business\SystemImport\SystemImport.cs:line 61
   at APP.Business.Class1.Main() in C:\_source\Client\materials-management-application\APP.Business\Class1.cs:line 11
```

**Comment by silkfire** [comment]
What's the actual exception message?

**Comment by jehugaleahsa** [comment]
I am researching this right now. The exception is a `NullReferenceException`. I am adding some code right now that will perform a check prior to assigning the values for `null`. Most importantly, it will result in a `FlatFileException` being thrown instead, with a message along the lines of "Encountered a null when assigning to the non-nullable property 'CreatedOn'.".

Doing this check for every record in the file had a minor performance impact, so I am including some optimizations so that this check is only performed for non-nullable types, such as `DateTime`, but will be otherwise ignored for class types (e.g., `string`) and nullable types (e.g., `DateTime?`).

Eventually, I will probably provide additional diagnostics, such as the record number. Expect a release later today.
