### ISSUE TITLE
OutOfMemoryException on large files

### ISSUE THREAD

**Issue by svaldetero** [jehugaleahsa/FlatFiles#86]
**Describe the bug**
Out of memory exceptions with *extremely* large files

**To Reproduce**
I have a fixed-width file (that is also comma-separated). The lines are ~1500 characters long, there are ~13 million rows, and it is ~20GB in size. I am using the `IFixedLengthTypedReader` from a `IFixedLengthTypeMapper`. I used the `.CustomMapping().WithReader()` to define the widths and destination properties. There are 90+ columns in the file. Using `while(IFixedLengthTypedReader.Read())` to loop throw the rows. After ~ 1.5 million rows, I get an out of memory exception in RetryReader. Looking at VS diagnostics, it looks like StringBuilder is the culprit. Here's the stack trace

``` 
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.Append(Char value, Int32 repeatCount)
   at System.Text.StringBuilder.Append(Char value)
   at FlatFiles.RetryReader.Read()
   at FlatFiles.FixedLengthRecordParser.SeparatorRecordReader.ReadRecord()
   at FlatFiles.FixedLengthReader.ParsePartitions()
   at FlatFiles.FixedLengthReader.Read()
```
There's no way for me to release that memory. This is not from the objects created.

**Expected behavior**
I expect to not get an out of memory exception just from looping over the rows in the file. I'm not even doing anything with the mapped object.

**Screenshots**
n/a

**Version:**
5.0.1

**Additional context**
n/a

**Comment by jehugaleahsa** [comment]
I had concerns when I added that code to capture an entire line. I had to
convince myself it wouldn't be a problem because that memory gets cleared
between each row. It only hangs out in the reader long enough to broadcast
it with events, if necessary. 1500 characters doesn't seem like it would
cause a problem.

I'll take a look, just to be sure.

**Comment by jehugaleahsa** [comment]
I figured it out. Check out 5.0.2 once it becomes available from NuGet. Let me know if you encounter any issues. Thanks for the feedback and diagnostic information.

**Comment by jehugaleahsa** [comment]
Closing due to inactivity.
